package com.lootingbag;

import java.util.Arrays;
import java.util.HashSet;
import java.util.stream.Collectors;
import static net.runelite.api.gameval.ItemID.*;

public class GeUntradables
{

	/**
	 * All ItemIDs for items that are tradeable but cannot be bought/sold on the Grand Exchange
	 * Scraped from <a href="https://oldschool.runescape.wiki/w/Grand_Exchange/Non-tradeable_items"/>
	 */
	private static final int[] ITEM_IDS = new int[]
	{
		COINS,

		// Burnt/inedible food
		BURNTFISH1, BURNTFISH2, BURNTFISH3,
		BURNTFISH4, BURNTFISH5, BURNT_SWORDFISH,
		BURNT_LOBSTER, BURNT_SHARK,
		BURNT_MANTARAY, BURNT_SEATURTLE,
		BURNT_CAKE, BURNT_STEW,
		BURNT_CURRY, BURNT_CHICKEN, BURNT_MEAT,
		BURNT_GNOMEBOWL, BURNT_CRUNCHIES, BURNT_BATTA,
		BURNT_PIZZA, BURNT_BREAD, BURNT_PIE, BURNT_OOMLIE,
		BURNT_OOMLIE, TBWT_BURNT_KARAMBWAN, BURNT_SNAIL, BURNT_EEL,
		BURNT_CAVE_EEL, SWEETCORN_BURNT, TBW_SPIDER_ON_STICK_BURNT, POTATO_BURNT,
		BOWL_EGG_BURNT, BOWL_ONION_BURNT, BOWL_MUSHROOM_BURNT,
		SPIT_BURNED_RABBIT_MEAT,
		_100_JUBBLY_MEAT_BURNED,
		BURNT_MONKFISH, BURNT_SHRIMP, SPIT_BURNED_BIRD_MEAT, SPIT_BURNED_BEAST_MEAT,
		HUNTING_RAW_FISH_SPECIAL_BURNT,
		BURNT_DARK_CRAB, BURNT_ANGLERFISH,
		RAIDS_FISH_BURNT, RAIDS_BAT_BURNT,
		RUINED_CHOMPY, ROTTEN_TOMATO, ROTTEN_FOOD,
		TBW_SPIDER_ON_SHAFT_BURNT, FAVOUR_HERBTEA_RUINED, UGTHANKI_KEBAB,

		// Item Packs
		PACK_VIAL_WATER,
		PACK_FEATHER, PACK_FISHING_BAIT,  PACK_AIRRUNE,
		PACK_WATERRUNE, PACK_EARTHRUNE, PACK_FIRERUNE,
		PACK_MINDRUNE, PACK_CHAOSRUNE,
		PACK_OJIBWAY_BIRD_SNARE, PACK_BOX_TRAP, PACK_MAGIC_IMP_BOX,
		PLATINUM, PACK_PLANT_POT_COMPOST, PACK_SACK,
		PACK_BASKET,
		PACK_AIRRUNE_TZHAAR, PACK_WATERRUNE_TZHAAR, PACK_EARTHRUNE_TZHAAR,
		PACK_FIRERUNE_TZHAAR,

		// Fire Arrows
		UNLITARROW, LITARROW, IRON_UNLITARROW, IRON_LITARROW,
		STEEL_UNLITARROW, STEEL_LITARROW, MITHRIL_UNLITARROW, MITHRIL_LITARROW,
		ADAMANT_UNLITARROW, ADAMANT_LITARROW, RUNE_UNLITARROW,
		RUNE_LITARROW, DRAGON_UNLITARROW, DRAGON_LITARROW,

		// Satchels
		TOL_PLAIN_SACK_DUMMY, TOL_GREEN_SACK_DUMMY,
		TOL_RED_SACK_DUMMY, TOL_BLACK_SACK_DUMMY, TOL_GOLD_SACK_DUMMY, TOL_RUNE_SACK_DUMMY,

		// Books
		NEWCOMER_MAP, BOOK_OF_ASTROLOGY, FLIER, FLIER_PRIF,
		ROVING_CRYSTAL_BOOK, ROVING_CADARN_BOOK,
		QIP_SOA_NEWSPAPER2, ARRAVCERTIFICATE_LFT, ARRAVCERTIFICATE_RHT,
		OBSERVATORY_GLASSBLOWING_BOOK,

		// Cosmetics
		EASTER18_HANDEGG_LIGHT, EASTER18_HANDEGG_BALANCE, EASTER18_HANDEGG_CHAOS,

		// Quest items
		PHOENIXKEY2, PHOENIX_CROSSBOW, MISC_KEY,
		MM_REINITIALISATION_HINT, DAMP_TINDERBOX,
		RAW_BEEF_UNDEAD, RAW_CHICKEN_UNDEAD, COOKED_CHICKEN_UNDEAD, COOKED_MEAT_UNDEAD,
		BURGH_RUBBLE_BUCKET_1, BURGH_RUBBLE_BUCKET_2, BURGH_RUBBLE_BUCKET_3,
		BURGH_GENERALSTORE_CRATE, EMPTY_FISHFOOD_BOX,
		MDAUGHTER_MUD, MDAUGHTER_ROCK, MDAUGHTER_BROKEN_STICK,
		PETECANDLESTICK,
		BOWL_EMPTY_FILLIMAN,

		// Castle wars
		CASTLEWARS_BANDAGES, CASTLEWARS_TOOLKIT, CASTLEWARS_BARRICADE,
		CASTLEWARS_EXPLOSIVES_POTION, CASTLEWARS_CLIMBING_ROPE, CASTLEWARS_CATAPULT_ROCK,

		// Trouble Brewing
		BREW_BLUE_FLOWER, BREW_RED_FLOWER,

		// Misc.
		OGRE_POTION, OYSTEREMPTY, BUCKET_BAILING, BUCKET_BAILINGFULL,
		SMASHED_GLASS, ROOFTILE, ROCK,
		FELINEMEDAL,
		CRUSHED_GEMSTONE,
		RAWSWAMPPASTE,
		GROUND_BAT_BONES,
		REGICIDE_SULPHAR, REGICIDE_CLOTH, EMPTY_DYE_BOTTLE,
		VIKING_TANKARD_EMPTY, IRON_SICKLE,
		COCONUT_HALF, COCONUT_SHELL,
		BURGH_UNFINISHED_GUTHIX_BALANCE_1, POH_TEA_LEAVES, PEST_FIELD_RATION,
		II_ANCHOVY_PASTE,
		BIRD_NEST_DECENTSEEDS,
		TEMPOROSS_DAMP_EGG, TOA_LOOT_POO, HW22_TRICK_BANANA,
		HW22_TRICK_SOCK, HW22_TRICK_EGG, HW22_TRICK_WOOL
	};

	public static HashSet<Integer> ItemIds = new HashSet<>(
		Arrays.stream(ITEM_IDS)
			.boxed()
			.collect(Collectors.toList())
	);
}
