package com.lootingbag;

import java.util.Arrays;
import java.util.HashSet;
import java.util.stream.Collectors;
import static net.runelite.api.ItemID.*;

public class GeUntradables
{

	/**
	 * All ItemIDs for items that are tradeable but cannot be bought/sold on the Grand Exchange
	 * Scraped from <a href="https://oldschool.runescape.wiki/w/Grand_Exchange/Non-tradeable_items"/>
	 */
	private static final int[] ITEM_IDS = new int[]
	{
		COINS_995,

		// Burnt/inedible food
		BURNT_FISH, BURNT_FISH_343, BURNT_FISH_357,
		BURNT_FISH_367, BURNT_FISH_369, BURNT_SWORDFISH,
		BURNT_LOBSTER, BURNT_SHARK,
		BURNT_MANTA_RAY, BURNT_SEA_TURTLE,
		BURNT_CAKE, BURNT_STEW,
		BURNT_CURRY, BURNT_CHICKEN, BURNT_MEAT,
		BURNT_GNOMEBOWL, BURNT_CRUNCHIES, BURNT_BATTA,
		BURNT_PIZZA, BURNT_BREAD, BURNT_PIE, BURNT_OOMLIE_WRAP,
		BURNT_OOMLIE, BURNT_KARAMBWAN, BURNT_SNAIL, BURNT_EEL,
		BURNT_CAVE_EEL, BURNT_SWEETCORN, BURNT_SPIDER, BURNT_POTATO,
		BURNT_EGG, BURNT_ONION, BURNT_MUSHROOM,
		BURNT_RABBIT,
		BURNT_JUBBLY,
		BURNT_MONKFISH, BURNT_SHRIMP, BURNT_BIRD_MEAT, BURNT_BEAST_MEAT,
		BURNT_RAINBOW_FISH,
		BURNT_DARK_CRAB, BURNT_ANGLERFISH,
		BURNT_FISH_20854, BURNT_BAT,
		RUINED_CHOMPY, ROTTEN_TOMATO, ROTTEN_FOOD,
		SPIDER_ON_SHAFT_6303, RUINED_HERB_TEA, UGTHANKI_KEBAB,

		// Item Packs
		WATERFILLED_VIAL_PACK,
		FEATHER_PACK, BAIT_PACK,  AIR_RUNE_PACK,
		WATER_RUNE_PACK, EARTH_RUNE_PACK, FIRE_RUNE_PACK,
		MIND_RUNE_PACK, CHAOS_RUNE_PACK,
		BIRD_SNARE_PACK, BOX_TRAP_PACK, MAGIC_IMP_BOX_PACK,
		PLATINUM_TOKEN, PLANT_POT_PACK, SACK_PACK,
		BASKET_PACK,
		TZHAAR_AIR_RUNE_PACK, TZHAAR_WATER_RUNE_PACK, TZHAAR_EARTH_RUNE_PACK,
		TZHAAR_FIRE_RUNE_PACK,

		// Fire Arrows
		BRONZE_FIRE_ARROW, IRON_FIRE_ARROW,
		STEEL_FIRE_ARROW, MITHRIL_FIRE_ARROW, ADAMANT_FIRE_ARROW,
		RUNE_FIRE_ARROW, DRAGON_FIRE_ARROW, AMETHYST_FIRE_ARROW,

		// Satchels
		PLAIN_SATCHEL, GREEN_SATCHEL,
		RED_SATCHEL, BLACK_SATCHEL, GOLD_SATCHEL, RUNE_SATCHEL,

		// Books
		NEWCOMER_MAP, ASTRONOMY_BOOK, FLYER,
		CRYSTAL_SINGING_FOR_BEGINNERS, CADARN_LINEAGE,
		NEWSPAPER_11171, HALF_CERTIFICATE, HALF_CERTIFICATE_11174,
		GLASSBLOWING_BOOK,

		// Cosmetics
		HOLY_HANDEGG, PEACEFUL_HANDEGG, CHAOTIC_HANDEGG,

		// Quest items
		WEAPON_STORE_KEY, PHOENIX_CROSSBOW, MISCELLANEOUS_KEY,
		SPARE_CONTROLS, DAMP_TINDERBOX,
		RAW_BEEF_4287, RAW_CHICKEN_4289, COOKED_CHICKEN_4291, COOKED_MEAT_4293,
		BUCKET_OF_RUBBLE, BUCKET_OF_RUBBLE_7624, BUCKET_OF_RUBBLE_7626,
		CRATE, AN_EMPTY_BOX,
		MUD, MUDDY_ROCK, BROKEN_POLE,
		PETES_CANDLESTICK,
		WASHING_BOWL,

		// Castle wars
		BANDAGES, TOOLKIT_4051, BARRICADE,
		EXPLOSIVE_POTION, CLIMBING_ROPE, ROCK_4043,

		// Trouble Brewing
		BLUE_FLOWERS_8936, RED_FLOWERS_8938,

		// Misc.
		POTION, EMPTY_OYSTER, BAILING_BUCKET,
		SMASHED_GLASS, TILE, ROCK,
		CAT_TRAINING_MEDAL,
		CRUSHED_GEM,
		RAW_SWAMP_PASTE,
		GROUND_BAT_BONES,
		SULPHUR, STRIP_OF_CLOTH, SAMPLE_BOTTLE,
		TANKARD, IRON_SICKLE,
		HALF_COCONUT, COCONUT_SHELL,
		GUTHIX_BALANCE_UNF_7658, TEA_LEAVES, FIELD_RATION,
		ANCHOVY_PASTE,
		BIRD_NEST_13653,
		DAMP_EGG, FOSSILISED_DUNG, BRUISED_BANANA,
		SMELLY_SOCK, SPOOKY_EGG, OLD_WOOL
	};

	public static HashSet<Integer> ItemIds = new HashSet<>(
		Arrays.stream(ITEM_IDS)
			.boxed()
			.collect(Collectors.toList())
	);
}
