package com.entrana;

import com.google.common.collect.ImmutableSet;
import net.runelite.api.ItemID;

import java.util.Set;

public class ProhibitedIDs {
    private static final Set<Integer> prohibitedIds = ImmutableSet.of(
            ItemID.CUTTHROAT_FLAG,
            ItemID.GILDED_SMILE_FLAG,
            ItemID.BRONZE_FIST_FLAG,
            ItemID.LUCKY_SHOT_FLAG,
            ItemID.TREASURE_FLAG,
            ItemID.PHASMATYS_FLAG,
            ItemID.BANNER,
            ItemID.BANNER_8652,
            ItemID.BANNER_8654,
            ItemID.BANNER_8656,
            ItemID.BANNER_8658,
            ItemID.BANNER_8660,
            ItemID.BANNER_8662,
            ItemID.BANNER_8664,
            ItemID.BANNER_8666,
            ItemID.BANNER_8668,
            ItemID.BANNER_8670,
            ItemID.BANNER_8672,
            ItemID.BANNER_8674,
            ItemID.BANNER_8676,
            ItemID.BANNER_8678,
            ItemID.BANNER_8680,
            ItemID.ARCEUUS_BANNER,
            ItemID.GREEN_BANNER,
            ItemID.HOSIDIUS_BANNER,
            ItemID.LOVAKENGJ_BANNER,
            ItemID.PISCARILIUS_BANNER,
            ItemID.PROTEST_BANNER,
            ItemID.SHATTERED_BANNER,
            ItemID.SHAYZIEN_BANNER,
            ItemID.TRAILBLAZER_BANNER,
            ItemID.SARADOMIN_BANNER_11891,
            ItemID.ZAMORAK_BANNER_11892,
            ItemID.MAGIC_BUTTERFLY_NET,
            ItemID.ANCIENT_HILT,
            ItemID.SARADOMIN_HILT,
            ItemID.BANDOS_HILT,
            ItemID.ZAMORAK_HILT,
            ItemID.ARMADYL_HILT,
            ItemID.GODSWORD_BLADE,
            ItemID.GODSWORD_SHARD_1,
            ItemID.GODSWORD_SHARD_2,
            ItemID.GODSWORD_SHARD_3,
            ItemID.HAM_JOINT,
            ItemID.SWIFT_BLADE,
            ItemID.IMCANDO_HAMMER,
            ItemID.CANNON_BASE,
            ItemID.CANNON_STAND,
            ItemID.CANNON_BARRELS,
            ItemID.CANNON_FURNACE,
            ItemID.CANNON_BASE_OR,
            ItemID.CANNON_STAND_OR,
            ItemID.CANNON_BARRELS_OR,
            ItemID.CANNON_FURNACE_OR,
            ItemID.BABY_IMPLING_JAR,
            ItemID.YOUNG_IMPLING_JAR,
            ItemID.GOURMET_IMPLING_JAR,
            ItemID.EARTH_IMPLING_JAR,
            ItemID.ESSENCE_IMPLING_JAR,
            ItemID.ECLECTIC_IMPLING_JAR,
            ItemID.NATURE_IMPLING_JAR,
            ItemID.MAGPIE_IMPLING_JAR,
            ItemID.NINJA_IMPLING_JAR,
            ItemID.DRAGON_IMPLING_JAR,
            ItemID.LUCKY_IMPLING_JAR,
            ItemID.CRYSTAL_IMPLING_JAR,
            ItemID.SUPPLY_CRATE,
            ItemID.SPOILS_OF_WAR,
            ItemID.BUTTERFLY_NET,
            ItemID.PROSPECTOR_BOOTS,
            ItemID.PROSPECTOR_HELMET,
            ItemID.PROSPECTOR_JACKET,
            ItemID.PROSPECTOR_LEGS,
            ItemID.GOLDEN_PROSPECTOR_BOOTS,
            ItemID.GOLDEN_PROSPECTOR_HELMET,
            ItemID.GOLDEN_PROSPECTOR_JACKET,
            ItemID.GOLDEN_PROSPECTOR_LEGS
    );

    public static boolean contains(int id) {
        return prohibitedIds.contains(id);
    }
}
